/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.TurmaDAO;
import dao.AlunoDAO;
import model.Turma;
import model.Aluno;
import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.logging.Logger;

/**
 *
 * @author davis
 */
public class MatriculaAlunoView extends javax.swing.JFrame {
    private TurmaDAO turmaDAO = new TurmaDAO();
    private AlunoDAO alunoDAO = new AlunoDAO();
    private static final Logger logger = Logger.getLogger(MatriculaAlunoView.class.getName());

    /**
     * Creates new form MatriculaAlunoView
     */
    public MatriculaAlunoView() {
        setTitle("Matrícula de Aluno em Turma");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(600, 400);
        setLocationRelativeTo(null);
        initComponents();
        carregarAlunos();
        carregarTurmas();
        atualizarTabela();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbAluno = new javax.swing.JComboBox<>();
        cmbTurma = new javax.swing.JComboBox<>();
        btnMatricular = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        scrollMatriculados = new javax.swing.JScrollPane();
        tabelaMatriculados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnMatricular.setText("Matricular");

        btnRemover.setText("Remover");

        tabelaMatriculados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollMatriculados.setViewportView(tabelaMatriculados);

        jLabel1.setText("Aluno:");

        jLabel2.setText("Turma:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnMatricular)
                                    .addGap(70, 70, 70)
                                    .addComponent(btnRemover))
                                .addComponent(cmbAluno, javax.swing.GroupLayout.Alignment.LEADING, 0, 419, Short.MAX_VALUE)
                                .addComponent(cmbTurma, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(scrollMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMatricular)
                            .addComponent(btnRemover))))
                .addGap(37, 37, 37)
                .addComponent(scrollMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MatriculaAlunoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMatricular;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<String> cmbAluno;
    private javax.swing.JComboBox<String> cmbTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane scrollMatriculados;
    private javax.swing.JTable tabelaMatriculados;
    // End of variables declaration//GEN-END:variables

    private void carregarAlunos() {
        cmbAluno.removeAllItems();
        List<Aluno> alunos = alunoDAO.listarTodos();
        for (Aluno a : alunos) {
            cmbAluno.addItem(a);
        }
        cmbAluno.setSelectedIndex(-1);
    }
    
    private void carregarTurmas() {
        cmbTurma.removeAllItems();
        List<Turma> turmas = turmaDAO.listarTodos();
        for (Turma t : turmas) {
            cmbTurma.addItem(t);
        }
        cmbTurma.setSelectedIndex(-1);
    }
    
    private void atualizarTabela() {
        Turma turma = (Turma) cmbTurma.getSelectedItem();
        if (turma == null) {
            tabelaMatriculados.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {}, new String[] {"Matrícula", "Nome", "Telefone"}));
            return;
        }

        List<Aluno> alunos = turmaDAO.listarAlunosMatriculados(turma.getId());
        String[] colunas = {"Matrícula", "Nome", "Telefone"};
        Object[][] dados = new Object[alunos.size()][3];

        for (int i = 0; i < alunos.size(); i++) {
            Aluno a = alunos.get(i);
            dados[i][0] = a.getMatricula();
            dados[i][1] = a.getNome();
            dados[i][2] = a.getTelefone();
        }
        tabelaMatriculados.setModel(new javax.swing.table.DefaultTableModel(dados, colunas));
    }
}

