/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.RelatorioController;
import java.time.LocalDate;
import java.util.Map;
import javax.swing.JOptionPane;
import java.util.logging.Logger;

/**
 *
 * @author davis
 */
public class RelatorioView extends javax.swing.JFrame {   
    private final RelatorioController relatorioController = new RelatorioController();
    private static final Logger logger = Logger.getLogger(RelatorioView.class.getName());

    /**
     * Creates new form RelatorioView
     */
    public RelatorioView() {
        initComponents();
        preencherComboBoxMes();
        preencherComboBoxAno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbAno = new javax.swing.JComboBox<>();
        btnGerarRelatorioMensal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGastoRealizadoAula = new javax.swing.JLabel();
        txtGastoPrevisto = new javax.swing.JLabel();
        txtReceitaArrecadada = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnGerarRelatorioAnual = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtReceitaPrevista = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtGastoRealizado = new javax.swing.JLabel();
        txtGastoRealizadoProfessor = new javax.swing.JLabel();
        txtGastoRealizadoManual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar Relatórios");
        setResizable(false);

        jLabel2.setText("Mês:");

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Ano:");

        cmbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGerarRelatorioMensal.setText("Gerar Relatório Mensal");
        btnGerarRelatorioMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioMensalActionPerformed(evt);
            }
        });

        jLabel1.setText("Receita Arrecadada:");

        jLabel3.setText("Gasto Realizado:");

        jLabel5.setText("Gasto Previsto:");

        txtGastoRealizadoAula.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        txtGastoRealizadoAula.setForeground(new java.awt.Color(60, 60, 60));
        txtGastoRealizadoAula.setText("R$ 0,00");

        txtGastoPrevisto.setText("R$ 0,00");

        txtReceitaArrecadada.setText("R$ 0,00");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnGerarRelatorioAnual.setText("Gerar Relatório Anual");
        btnGerarRelatorioAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioAnualActionPerformed(evt);
            }
        });

        jLabel6.setText("Receita Prevista:");

        txtReceitaPrevista.setText("R$ 0,00");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(70, 70, 70));
        jLabel7.setText("Gasto Aulas:");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 70, 70));
        jLabel8.setText("Gasto Manuais:");

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(70, 70, 70));
        jLabel9.setText("Gasto Professores:");

        txtGastoRealizado.setText("R$ 0,00");

        txtGastoRealizadoProfessor.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        txtGastoRealizadoProfessor.setForeground(new java.awt.Color(60, 60, 60));
        txtGastoRealizadoProfessor.setText("R$ 0,00");

        txtGastoRealizadoManual.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        txtGastoRealizadoManual.setForeground(new java.awt.Color(60, 60, 60));
        txtGastoRealizadoManual.setText("R$ 0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbAno, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGerarRelatorioMensal)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel9)
                                .addComponent(jLabel8))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGastoPrevisto)
                            .addComponent(txtReceitaPrevista)
                            .addComponent(txtReceitaArrecadada)
                            .addComponent(txtGastoRealizadoAula)
                            .addComponent(txtGastoRealizado)
                            .addComponent(txtGastoRealizadoProfessor)
                            .addComponent(txtGastoRealizadoManual)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGerarRelatorioAnual)
                                .addGap(53, 53, 53)
                                .addComponent(btnVoltar)))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerarRelatorioMensal)
                    .addComponent(btnVoltar)
                    .addComponent(btnGerarRelatorioAnual))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtReceitaArrecadada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtReceitaPrevista))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGastoRealizado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGastoRealizadoAula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGastoRealizadoProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGastoRealizadoManual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGastoPrevisto))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRelatorioMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioMensalActionPerformed
        try {
            if (cmbMes.getSelectedIndex() == -1 || cmbAno.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Selecione mês e ano para o relatório.");
                return;
            }
            String mesStr = (String) cmbMes.getSelectedItem();
            int mes = Integer.parseInt(mesStr.substring(0, 2));
            int ano = Integer.parseInt((String) cmbAno.getSelectedItem());
            
            double receitaArrecadada = 0;
            double receitaFutura = 0;
            
            Map<String, Double> gasto = relatorioController.detalharMensalGastoRealizado(mes, ano);
            double gastoRealizado = gasto.get("total");
            double gastoAulas = gasto.get("aulas");
            double gastoProfessores = gasto.get("professores");
            double gastoManuais = gasto.get("manuais");
            
            double gastoPrevisto = relatorioController.calcularMensalGastoPrevisto(mes, ano);
            
            if(mes > LocalDate.now().getMonthValue()) {
                receitaFutura = relatorioController.calcularMensalReceitaArrecadada(mes, ano);
            } else {
                receitaArrecadada = relatorioController.calcularMensalReceitaArrecadada(mes, ano);
            }
            
            txtReceitaArrecadada.setText(String.format("R$ %.2f", receitaArrecadada));
            txtReceitaPrevista.setText(String.format("R$ %.2f", receitaFutura));
            txtGastoRealizado.setText(String.format("R$ %.2f", gastoRealizado));
            txtGastoRealizadoAula.setText(String.format("R$ %.2f", gastoAulas));
            txtGastoRealizadoProfessor.setText(String.format("R$ %.2f", gastoProfessores));
            txtGastoRealizadoManual.setText(String.format("R$ %.2f", gastoManuais));
            txtGastoPrevisto.setText(String.format("R$ %.2f", gastoPrevisto));  
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valor hora médio inválido!");
        }
    }//GEN-LAST:event_btnGerarRelatorioMensalActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose(); // Fecha a janela atual
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnGerarRelatorioAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioAnualActionPerformed
        try {
            if (cmbAno.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Selecione o ano para o relatório.");
                return;
            }
            int ano = Integer.parseInt((String) cmbAno.getSelectedItem());

            double receitaArrecadada = relatorioController.calcularAnualReceitaArrecadada(ano);
            double receitaPrevista = relatorioController.calcularAnualReceitaPrevista(ano);
            
            Map<String, Double> gasto = relatorioController.detalharAnualGastoRealizado(ano);
            double gastoRealizado = gasto.get("total");
            double gastoAulas = gasto.get("aulas");
            double gastoProfessores = gasto.get("professores");
            double gastoManuais = gasto.get("manuais");
            
            double gastoPrevisto = relatorioController.calcularAnualGastoPrevisto(ano);

            txtReceitaArrecadada.setText(String.format("R$ %.2f", receitaArrecadada));
            txtReceitaPrevista.setText(String.format("R$ %.2f", receitaPrevista));
            txtGastoRealizado.setText(String.format("R$ %.2f", gastoRealizado));
            txtGastoRealizadoAula.setText(String.format("R$ %.2f", gastoAulas));
            txtGastoRealizadoProfessor.setText(String.format("R$ %.2f", gastoProfessores));
            txtGastoRealizadoManual.setText(String.format("R$ %.2f", gastoManuais));
            txtGastoPrevisto.setText(String.format("R$ %.2f", gastoPrevisto));  
            

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valor hora médio inválido!");
        }   
    }//GEN-LAST:event_btnGerarRelatorioAnualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RelatorioView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarRelatorioAnual;
    private javax.swing.JButton btnGerarRelatorioMensal;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbAno;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel txtGastoPrevisto;
    private javax.swing.JLabel txtGastoRealizado;
    private javax.swing.JLabel txtGastoRealizadoAula;
    private javax.swing.JLabel txtGastoRealizadoManual;
    private javax.swing.JLabel txtGastoRealizadoProfessor;
    private javax.swing.JLabel txtReceitaArrecadada;
    private javax.swing.JLabel txtReceitaPrevista;
    // End of variables declaration//GEN-END:variables
    
    private void preencherComboBoxMes() {
        String[] meses = {
            "01 - Janeiro", "02 - Fevereiro", "03 - Março", "04 - Abril",
            "05 - Maio", "06 - Junho", "07 - Julho", "08 - Agosto",
            "09 - Setembro", "10 - Outubro", "11 - Novembro", "12 - Dezembro"
        };
        cmbMes.removeAllItems();
        for (String mes : meses) cmbMes.addItem(mes);
        int mesAtual = java.time.LocalDate.now().getMonthValue();
        cmbMes.setSelectedIndex(mesAtual - 1);
    }

    private void preencherComboBoxAno() {
        int anoAtual = LocalDate.now().getYear();
        cmbAno.removeAllItems();
        for (int i = anoAtual - 5; i <= anoAtual + 5; i++) cmbAno.addItem(String.valueOf(i));
        cmbAno.setSelectedItem(String.valueOf(anoAtual));
    }
}
